"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var parser_1 = require("./exchange_parser/parser");
var redis_database_1 = require("./exchange_parser/redis-database");
var websocket_server_1 = require("./exchange_parser/websocket-server");
var isProd = false;
var database = new redis_database_1.RedisDatabase();
var parser = new parser_1.Parser(database);
var websocketServer = new websocket_server_1.WebSocketServer();
parser.onPriceChanged.push({ listener: websocketServer.onPriceChangedListener, root: websocketServer });
setTimeout(function () { return websocketServer.start(); }, 1);
setTimeout(function () { return parser.start(); }, 1);
