<?php

namespace AppBundle\Repository;

/**
 * AssetCharacteristicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetCharacteristicRepository extends \Doctrine\ORM\EntityRepository
{
}
