<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUserNotesOrderedByIdDesc(User $user)
    {
        return $this->createQueryBuilder('note')
            ->where('note.user = :user')
            ->orderBy('note.id', 'desc')
            ->setParameter('user', $user);
    }

}
