<?php

namespace AppBundle\Repository;

/**
 * PageCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
