<?php

namespace AppBundle\Repository;

/**
 * PromoCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoCodeRepository extends \Doctrine\ORM\EntityRepository
{

    public function paginate($page, $take = 15)
    {
        return $this
            ->createQueryBuilder('promo_code')
            ->orderBy('promo_code.id', 'desc');
    }

    public function findAllOrderedByIdDesc()
    {
        return $this->createQueryBuilder('promo_code')
            ->orderBy('promo_code.id', 'desc');
    }

}
