api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

binary_trade:
    resource: "@BinaryTradeBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type:     annotation
